export const POPULARCITIES_LOADING = 'POPULARCITIES_LOADING'
export const POPULARCITIES_SUCCESS = 'POPULARCITIES_SUCCESS'
export const POPULARCITIES_FAILED = 'POPULARCITIES_FAILED'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'